---
abstract: '(DEPRECATED) installing and finding Prototype Carousel component'
author:
  - 'Graham TerMarsch (cpan@howlingfrog.com)'
build_requires:
  Test::Exception: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-Prototype-Carousel
provides:
  Alien::Prototype::Carousel:
    file: lib/Alien/Prototype/Carousel.pm
    version: v0.26.3
requires:
  Alien::scriptaculous: '0'
  perl: v5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: v0.26.3
x_deprecated: 1
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
